### ISSUE TITLE
Hello world app doesn't run. dlangide 5.36 os x 10.11.2

### ISSUE THREAD

**Issue by dchapman2146** [buggins/dlangide#100]
I started dlangide, selected Hello world app and new workspace, selected run without debugging and got messages that the build worked but it couldn't run the program.

Builder finished with result 0
Starting debugger for /Users/davidcha/newworkspace/newproject/bin/newproject
Cannot run program /Users/davidcha/newworkspace/newproject/bin/newproject

[cannot_run_program_gui_transcript.txt](https://github.com/buggins/dlangide/files/93700/cannot_run_program_gui_transcript.txt)
[cannot_run_program_terminal_transcript.txt](https://github.com/buggins/dlangide/files/93701/cannot_run_program_terminal_transcript.txt)

**Comment by dchapman2146** [comment]
I found in the wiki that I need xQuartz so I installed it. I also rebuilt dlangide. The results are similar. Here is the terminal transcript. I didn't include the gui transcript this time because the program appeared to hang and I force quit out of it and so I lost the guy transcript. It was similar to the one without xQuartz.

[cannot_run_program_terminal_transcript_with_xquartz.txt](https://github.com/buggins/dlangide/files/93724/cannot_run_program_terminal_transcript_with_xquartz.txt)

**Comment by buggins** [comment]
Run -- starts debugging, requires GDB installed.
try "Run without debug" or install GDB.

**Comment by buggins** [comment]
Sorry, did not notice that it's w/o debugging

**Comment by dchapman2146** [comment]
Now I learned that gdb doesn’t come with Xcode 7 in 10.11. And I learned that installing gdb requires getting it codesigned. Not tonight. 

In order to get dlangide to install I had to install libSDL2. Macports put it in /opt/local/lib. dlangide or dub couldn’t see libSDL2 in /opt/local/lib even when I added LD_LIBRARY_PATH /opt/local/lib to my environment variables. I hacked around the problem by copying libSDL2 to /usr/local/lib. I use tcsh not bash.

1. Could this be related to the problem of the hello world not running?
2. Did I do something wrong?
3. Did dlangide or dub do something wrong and I should report this as a bug?
4. Did apple change the way dynamic libraries are loaded and there is a different way to tell dlangide where libSDL2 is?

**Comment by buggins** [comment]
Let me check

**Comment by buggins** [comment]
Looks like Menu/Debug/Run without debugging works exactly as Run with debugging

**Comment by buggins** [comment]
Fixed in v0.5.37
Please confirm that fix works for you.

To run w/o debug: press Ctrl+F5 or Menu/Debug/Start without debugging

To enable GDB, under OSX you need to sign GDB executable.
https://sourceware.org/gdb/wiki/BuildingOnDarwin

**Comment by buggins** [comment]
works on my mac mini

**Comment by dchapman2146** [comment]
I tried 5.39 and the issue is still there. I tried both the pulldown menu and ctrl+F5. Since I am running on a MacBook I have to use fn+ctrl+F5.

[cannot_run_program_dlangide_5_39.txt](https://github.com/buggins/dlangide/files/95136/cannot_run_program_dlangide_5_39.txt)

**Comment by dchapman2146** [comment]
I only have dmd installed right now.

**Comment by buggins** [comment]
xterm executable is not found
I don't remember how I installed xterm
DlangIDE requires some external terminal application which can be accessible via tty device
Terminal executable can be set in Edit/Preferences/Terminal

**Comment by buggins** [comment]
Specifying /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal as terminal executable does not work for me.

**Comment by dchapman2146** [comment]
I put /usr/X11/bin in my path. Hello world ran and displayed in the X11 window with the rest of my display black. Then I hit return and the xterm went away leaving my entire display black. I suspect that some X11 configuration magic is needed to get my display back. It is a macbook pro. I hope this jogs your memory and you can tell me the answer.

Dave

**Comment by buggins** [comment]
I don't see such effects. Are you using xQuartz as X server?

**Comment by buggins** [comment]
BTW, I believe my xterm is installed by MonoDevelop setup.

**Comment by dchapman2146** [comment]
I think so. I installed xQuarts and in the X11/bin directory I see xQuartz. So Yes.

**Comment by dchapman2146** [comment]
I found a solution. 

The short version is go into the X11 preferences and uncheck the full screen box. I’m out of time right now. I’ll send more information later. Is it OK if I put it in the wiki?

I think so. I installed xQuarts and in the X11/bin directory I see xQuartz. So Yes.

**Comment by buggins** [comment]
Yes. It would be great to add it in Installation section of wiki

**Comment by buggins** [comment]
Closing this issue
