### ISSUE TITLE
File Browse Dialogue Doesn't Display Files and Breaks Text on Main Window

### ISSUE THREAD

**Issue by DmetriWolf** [buggins/dlangide#124]
[Screencap](http://imgur.com/9HL5YAh)
Using 64-bit Linux Mint 17.2

The IDE looks normal until I try to open a file by opening the directory browser. No text appears in the list. Even after closing the dialogue the text in the main window is altered, mostly with having block characters replacing the final character. Hovering over the links under Useful Links on the start page turns all but the last character into blocks for the duration of the hover (except the final link which unlike the other links ends with a block and that block remains but changes colour when hovered over). When I've clicked a menu bar item to display its drop down list all the other menu bar items end in a block except the item to the left of it, otherwise just the last character of Help is a block. [When trying to edit text there's no blinking cursor, the lines end with a block, and the line numbers are all blocks.](http://imgur.com/3uqK8IX)

The other dialogues don't seem to cause this behavior, but they are affected by it.

**Comment by g4z3r** [comment]
Hmm, I've found this problem on my nvidia card.

**Comment by g4z3r** [comment]
My [optimization commit](https://github.com/buggins/dlangui/commit/4d16c29506d4b5c1456edab5d56989a32c67fe6a) into dlangui caused it. I will try to fix.

**Comment by g4z3r** [comment]
[Fixed](https://github.com/buggins/dlangui/pull/165)

**Comment by DmetriWolf** [comment]
I don't think that fixed it, still getting the exact same issue...
I have a Nvidia card: GeForce GTX 560 Ti.

**Comment by g4z3r** [comment]
Maybe it is because dlangui dependency did not still updated.

**Comment by DmetriWolf** [comment]
You're right, problem solved, thankyou!
But Jesus, dub did not want to let me upgrade without `dub clean-caches`.

**Comment by buggins** [comment]
I see similar problems under Windows.
OpenGL drawing of text in additional windows do not work - it's why I'm using popup widgets instead of windows in dialogs for this platform
